/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.ApplicationContext;
import core.controllers.responses.Response;
import core.models.entities.Doctor;
import core.models.entities.Patient;
import core.models.entities.User;
import java.awt.Color;
import java.util.HashMap;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class LoginView extends javax.swing.JFrame {

    private int x, y;
    private final ApplicationContext context;

    public LoginView() {
        initComponents();
        this.context = ApplicationContext.getInstance();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new packagee.PanelRound();
        pnlTitleBar = new packagee.PanelRound();
        btnCloseWindow = new javax.swing.JButton();
        tabMain = new javax.swing.JTabbedPane();
        pnlLoginForm = new packagee.PanelRound();
        lblLoginTitle = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        lblLoginUsername = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pnlRegister = new javax.swing.JPanel();
        lblRegisterFirstname = new javax.swing.JLabel();
        txtRegisterFirstname = new javax.swing.JTextField();
        lblRegisterLastname = new javax.swing.JLabel();
        txtRegisterLastname = new javax.swing.JTextField();
        lblRegisterId = new javax.swing.JLabel();
        txtRegisterId = new javax.swing.JTextField();
        lblRegisterPhone = new javax.swing.JLabel();
        lblRegisterEmail = new javax.swing.JLabel();
        txtRegisterPhone = new javax.swing.JTextField();
        lblRegisterUsername = new javax.swing.JLabel();
        txtRegisterEmail = new javax.swing.JTextField();
        lblRegisterPassword = new javax.swing.JLabel();
        txtRegisterUsername = new javax.swing.JTextField();
        txtRegisterPassword = new javax.swing.JTextField();
        lblRegisterGender = new javax.swing.JLabel();
        lblRegisterConfirmPassword = new javax.swing.JLabel();
        txtRegisterConfirmPassword = new javax.swing.JTextField();
        cmbRegisterGender = new javax.swing.JComboBox<>();
        btnRegisterPatient = new javax.swing.JButton();
        lblRegisterAddress = new javax.swing.JLabel();
        txtRegisterAddress = new javax.swing.JTextField();
        lblRegisterBirthdate = new javax.swing.JLabel();
        txtRegisterBirthdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlBackground.setRadius(50);

        pnlTitleBar.setRadius(50);
        pnlTitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitleBarMouseDragged(evt);
            }
        });
        pnlTitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitleBarMousePressed(evt);
            }
        });

        btnCloseWindow.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCloseWindow.setText("X");
        btnCloseWindow.setBorderPainted(false);
        btnCloseWindow.setContentAreaFilled(false);
        btnCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloseWindow.setFocusable(false);
        btnCloseWindow.setRequestFocusEnabled(false);
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseWindow)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCloseWindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblLoginTitle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblLoginTitle.setText("LOGIN");

        txtLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginUsername.setText("USERNAME");

        txtLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginPassword.setText("PASSWORD");

        btnLogin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogin.setText("ENTER");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(pnlLoginForm);
        pnlLoginForm.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(lblLoginTitle)
                .addGap(481, 481, 481))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoginPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLoginUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblLoginTitle)
                .addGap(74, 74, 74)
                .addComponent(lblLoginUsername)
                .addGap(18, 18, 18)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginPassword)
                .addGap(18, 18, 18)
                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnLogin)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tabMain.addTab("Login", pnlLoginForm);

        lblRegisterFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterFirstname.setText("Firstname");

        txtRegisterFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegisterLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterLastname.setText("Lastname");

        txtRegisterLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegisterId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterId.setText("ID");

        txtRegisterId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegisterPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterPhone.setText("Gender");

        lblRegisterEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterEmail.setText("Phone");

        txtRegisterPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegisterUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterUsername.setText("Email");

        txtRegisterEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegisterPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterPassword.setText("User");

        txtRegisterUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtRegisterPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegisterGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterGender.setText("Password");

        lblRegisterConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterConfirmPassword.setText("Password confirmation");

        txtRegisterConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRegisterConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterConfirmPasswordActionPerformed(evt);
            }
        });

        cmbRegisterGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbRegisterGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        btnRegisterPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRegisterPatient.setText("Save");
        btnRegisterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPatientActionPerformed(evt);
            }
        });

        lblRegisterAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterAddress.setText("Address");

        txtRegisterAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegisterBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegisterBirthdate.setText("Birthdate");

        txtRegisterBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblRegisterGender))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRegisterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(lblRegisterPassword))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(txtRegisterConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(btnRegisterPatient))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblRegisterConfirmPassword))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblRegisterBirthdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRegisterBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblRegisterFirstname)
                                .addGap(34, 34, 34)
                                .addComponent(txtRegisterFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegisterLastname)
                            .addComponent(lblRegisterAddress))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtRegisterLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegisterId)
                                .addGap(30, 30, 30)
                                .addComponent(txtRegisterId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegisterPhone)
                                .addGap(26, 26, 26)
                                .addComponent(cmbRegisterGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtRegisterAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegisterEmail)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegisterPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRegisterUsername)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisterFirstname)
                    .addComponent(txtRegisterFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisterLastname)
                    .addComponent(txtRegisterLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisterId)
                    .addComponent(txtRegisterId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisterPhone)
                    .addComponent(cmbRegisterGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegisterBirthdate)
                        .addComponent(txtRegisterBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegisterAddress)
                        .addComponent(txtRegisterAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegisterEmail)
                        .addComponent(txtRegisterPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegisterUsername)
                        .addComponent(txtRegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(lblRegisterPassword)
                .addGap(18, 18, 18)
                .addComponent(txtRegisterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegisterGender)
                .addGap(18, 18, 18)
                .addComponent(txtRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegisterConfirmPassword)
                .addGap(18, 18, 18)
                .addComponent(txtRegisterConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRegisterPatient)
                .addGap(42, 42, 42))
        );

        tabMain.addTab("Patient register", pnlRegister);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(pnlTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabMain)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void pnlTitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Response response = context.getAuthController().login(txtLoginUsername.getText(), txtLoginPassword.getText());
        if (!ViewHelper.handleResponse(this, response, null)) {
            return;
        }

        long userId = ((Number) response.getData().get("id")).longValue();
        User selectedUser = context.findUserById(userId);
        context.setCurrentUser(selectedUser);

        this.setVisible(false);
        String role = (String) response.getData().get("role");
        switch (role) {
            case "admin" -> new AdminView(selectedUser).setVisible(true);
            case "doctor" -> new DoctorView(selectedUser, (Doctor) selectedUser).setVisible(true);
            case "patient" -> new PatientView(selectedUser, (Patient) selectedUser).setVisible(true);
            default -> this.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRegisterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        HashMap<String, String> data = new HashMap<>();
        data.put("id", txtRegisterId.getText());
        data.put("firstname", txtRegisterFirstname.getText());
        data.put("lastname", txtRegisterLastname.getText());
        data.put("gender", cmbRegisterGender.getSelectedIndex() == 0 ? "" : String.valueOf(cmbRegisterGender.getSelectedIndex() == 1));
        data.put("birthdate", txtRegisterBirthdate.getText());
        data.put("address", txtRegisterAddress.getText());
        data.put("phone", txtRegisterPhone.getText());
        data.put("email", txtRegisterEmail.getText());
        data.put("username", txtRegisterUsername.getText());
        data.put("password", txtRegisterPassword.getText());
        data.put("confirmPassword", txtRegisterConfirmPassword.getText());

        ViewHelper.handleResponse(this, context.getPatientController().registerPatient(data), () -> {
            txtRegisterFirstname.setText("");
            txtRegisterLastname.setText("");
            txtRegisterId.setText("");
            txtRegisterPhone.setText("");
            txtRegisterEmail.setText("");
            txtRegisterUsername.setText("");
            txtRegisterPassword.setText("");
            txtRegisterConfirmPassword.setText("");
            txtRegisterAddress.setText("");
            txtRegisterBirthdate.setText("");
            cmbRegisterGender.setSelectedIndex(0);
        });
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtRegisterConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Main entry point is main.Main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegisterPatient;
    private javax.swing.JComboBox<String> cmbRegisterGender;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblRegisterPassword;
    private javax.swing.JLabel lblRegisterGender;
    private javax.swing.JLabel lblRegisterConfirmPassword;
    private javax.swing.JLabel lblRegisterAddress;
    private javax.swing.JLabel lblRegisterBirthdate;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblRegisterFirstname;
    private javax.swing.JLabel lblRegisterLastname;
    private javax.swing.JLabel lblRegisterId;
    private javax.swing.JLabel lblRegisterPhone;
    private javax.swing.JLabel lblRegisterEmail;
    private javax.swing.JLabel lblRegisterUsername;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JTextField txtRegisterConfirmPassword;
    private javax.swing.JTextField txtRegisterAddress;
    private javax.swing.JTextField txtRegisterBirthdate;
    private javax.swing.JTextField txtLoginPassword;
    private javax.swing.JTextField txtRegisterFirstname;
    private javax.swing.JTextField txtRegisterLastname;
    private javax.swing.JTextField txtRegisterId;
    private javax.swing.JTextField txtRegisterPhone;
    private javax.swing.JTextField txtRegisterEmail;
    private javax.swing.JTextField txtRegisterUsername;
    private javax.swing.JTextField txtRegisterPassword;
    private packagee.PanelRound pnlBackground;
    private packagee.PanelRound pnlTitleBar;
    private packagee.PanelRound pnlLoginForm;
    // End of variables declaration//GEN-END:variables
}
