/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.ApplicationContext;
import core.controllers.responses.Response;
import core.models.entities.Administrator;
import core.models.entities.Patient;
import core.models.entities.Specialty;
import core.models.entities.User;
import core.observers.implementations.TableObserver;
import core.utils.EntitySerializer;
import core.utils.SpecialtyMapper;
import java.awt.Color;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class PatientView extends javax.swing.JFrame {

    private int x, y;
    private final ApplicationContext context;
    private final User user;
    private Patient patient;

    public PatientView(User user, Patient patient) {
        initComponents();
        this.context = ApplicationContext.getInstance();
        this.user = user;
        this.patient = patient;
        btnBackToAdmin.setVisible(user instanceof Administrator);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        loadPatientProfile();
        loadDoctorCombo();
        loadRoomTypes();
        loadAppointmentCombo();
        refreshAppointmentsTable();
        context.getStorage().attach(new TableObserver(this::refreshAppointmentsTable));
    }

    private void loadPatientProfile() {
        txtProfileFirstname.setText(patient.getFirstname());
        txtProfileLastname.setText(patient.getLastname());
        cmbProfileGender.setSelectedIndex(patient.isGender() ? 1 : 2);
        txtProfileBirthdate.setText(patient.getBirthdate().toString());
        txtProfileAddress.setText(patient.getAddress());
        txtProfilePhone.setText(String.valueOf(patient.getPhone()));
        txtProfileEmail.setText(patient.getEmail());
        txtProfileUsername.setText(patient.getUsername());
        txtProfilePassword.setText(patient.getPassword());
        txtProfileConfirmPassword.setText(patient.getPassword());
    }

    private void loadDoctorCombo() {
        cmbHospitalizationDoctor.removeAllItems();
        cmbHospitalizationDoctor.addItem("Select one");
        Response response = context.getDoctorController().getAllDoctors();
        if (response.getData() == null) {
            return;
        }
        List<HashMap<String, Object>> doctors = (List<HashMap<String, Object>>) response.getData().get("doctors");
        for (HashMap<String, Object> doctor : doctors) {
            cmbHospitalizationDoctor.addItem(doctor.get("id") + " - " + doctor.get("label"));
        }
    }

    private void loadRoomTypes() {
        cmbHospitalizationRoomType.removeAllItems();
        for (String roomType : EntitySerializer.serializeRoomTypes()) {
            cmbHospitalizationRoomType.addItem(roomType);
        }
    }

    private void loadAppointmentCombo() {
        cmbCancelAppointmentId.removeAllItems();
        cmbCancelAppointmentId.addItem("Select one");
        Response response = context.getAppointmentController().getPatientAppointments(patient.getId());
        if (response.getData() == null) {
            return;
        }
        List<HashMap<String, Object>> appointments = (List<HashMap<String, Object>>) response.getData().get("appointments");
        for (HashMap<String, Object> appointment : appointments) {
            if (!"COMPLETED".equals(appointment.get("status")) && !"CANCELED".equals(appointment.get("status"))) {
                cmbCancelAppointmentId.addItem(String.valueOf(appointment.get("id")));
            }
        }
    }

    private void refreshAppointmentsTable() {
        Response response = context.getAppointmentController().getPatientAppointments(patient.getId());
        DefaultTableModel model = (DefaultTableModel) tblPatientAppointments.getModel();
        model.setRowCount(0);
        if (response.getData() == null) {
            return;
        }
        List<HashMap<String, Object>> appointments = (List<HashMap<String, Object>>) response.getData().get("appointments");
        for (HashMap<String, Object> appointment : appointments) {
            model.addRow(new Object[]{
                appointment.get("id"),
                appointment.get("datetime"),
                appointment.get("doctorName"),
                appointment.get("specialty"),
                appointment.get("type"),
                appointment.get("status")
            });
        }
        loadAppointmentCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new packagee.PanelRound();
        pnlTitleBar = new packagee.PanelRound();
        btnCloseWindow = new javax.swing.JButton();
        lblPatientHeader = new javax.swing.JLabel();
        btnBackToAdmin = new javax.swing.JButton();
        tabPatientMain = new javax.swing.JTabbedPane();
        pnlProfile = new javax.swing.JPanel();
        scrHospitalizationReason = new javax.swing.JScrollPane();
        tblPatientAppointments = new javax.swing.JTable();
        btnRefreshAppointments = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlAppointments = new javax.swing.JPanel();
        lblPatientSubtitle = new javax.swing.JLabel();
        txtProfileFirstname = new javax.swing.JTextField();
        lblPatientTitle = new javax.swing.JLabel();
        txtProfileLastname = new javax.swing.JTextField();
        lblProfileFirstname = new javax.swing.JLabel();
        txtProfileBirthdate = new javax.swing.JTextField();
        lblProfileLastname = new javax.swing.JLabel();
        lblProfileGender = new javax.swing.JLabel();
        txtProfileEmail = new javax.swing.JTextField();
        lblProfileBirthdate = new javax.swing.JLabel();
        txtProfilePhone = new javax.swing.JTextField();
        lblProfileEmail = new javax.swing.JLabel();
        txtProfileAddress = new javax.swing.JTextField();
        txtProfilePassword = new javax.swing.JTextField();
        lblProfilePhone = new javax.swing.JLabel();
        lblProfileAddress = new javax.swing.JLabel();
        txtProfileConfirmPassword = new javax.swing.JTextField();
        btnUpdateProfile = new javax.swing.JButton();
        lblProfileUsername = new javax.swing.JLabel();
        txtProfileUsername = new javax.swing.JTextField();
        cmbProfileGender = new javax.swing.JComboBox<>();
        pnlHospitalization = new javax.swing.JPanel();
        lblProfilePassword = new javax.swing.JLabel();
        rdbAppointmentBySpecialty = new javax.swing.JRadioButton();
        rdbAppointmentByDoctor = new javax.swing.JRadioButton();
        sepAppointments = new javax.swing.JSeparator();
        lblProfileConfirmPassword = new javax.swing.JLabel();
        txtAppointmentDate = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        lblAppointmentType = new javax.swing.JLabel();
        lblAppointmentDoctorOrSpecialty = new javax.swing.JLabel();
        lblAppointmentDate = new javax.swing.JLabel();
        cmbAppointmentType = new javax.swing.JComboBox<>();
        btnRequestAppointment = new javax.swing.JButton();
        sepProfile = new javax.swing.JSeparator();
        lblAppointmentTime = new javax.swing.JLabel();
        lblAppointmentReason = new javax.swing.JLabel();
        lblHospitalizationReason = new javax.swing.JLabel();
        cmbHospitalizationDoctor = new javax.swing.JComboBox<>();
        txtHospitalizationDate = new javax.swing.JTextField();
        lblHospitalizationDate = new javax.swing.JLabel();
        lblHospitalizationDoctor = new javax.swing.JLabel();
        cmbHospitalizationRoomType = new javax.swing.JComboBox<>();
        lblHospitalizationRoomType = new javax.swing.JLabel();
        scrAppointmentsTable = new javax.swing.JScrollPane();
        txtAreaHospitalizationObservations = new javax.swing.JTextArea();
        btnRequestHospitalization = new javax.swing.JButton();
        lblHospitalizationObservations = new javax.swing.JLabel();
        lblCancelAppointmentId = new javax.swing.JLabel();
        lblCancelObservation = new javax.swing.JLabel();
        scrHospitalizationObservations = new javax.swing.JScrollPane();
        txtAreaCancelObservation = new javax.swing.JTextArea();
        btnCancelAppointment = new javax.swing.JButton();
        scrAppointmentReason = new javax.swing.JScrollPane();
        txtAreaHospitalizationReason = new javax.swing.JTextArea();
        scrCancelObservation = new javax.swing.JScrollPane();
        txtAreaAppointmentReason = new javax.swing.JTextArea();
        cmbCancelAppointmentId = new javax.swing.JComboBox<>();
        cmbAppointmentDoctorOrSpecialty = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlBackground.setRadius(50);

        pnlTitleBar.setRadius(50);
        pnlTitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitleBarMouseDragged(evt);
            }
        });
        pnlTitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitleBarMousePressed(evt);
            }
        });

        btnCloseWindow.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCloseWindow.setText("X");
        btnCloseWindow.setBorderPainted(false);
        btnCloseWindow.setContentAreaFilled(false);
        btnCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloseWindow.setFocusable(false);
        btnCloseWindow.setRequestFocusEnabled(false);
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        lblPatientHeader.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblPatientHeader.setText("PATIENT VIEW");

        btnBackToAdmin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnBackToAdmin.setText("Back");
        btnBackToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPatientHeader)
                .addGap(29, 29, 29)
                .addComponent(btnBackToAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseWindow)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCloseWindow))
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackToAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblPatientHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblPatientAppointments.setAutoCreateRowSorter(true);
        tblPatientAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrHospitalizationReason.setViewportView(tblPatientAppointments);

        btnRefreshAppointments.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRefreshAppointments.setText("Refresh");
        btnRefreshAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshAppointmentsActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(scrHospitalizationReason, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(btnRefreshAppointments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(scrHospitalizationReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshAppointments)
                    .addComponent(btnLogout))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tabPatientMain.addTab("Appointment history", pnlProfile);

        lblPatientSubtitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientSubtitle.setText("Firstname");

        txtProfileFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientTitle.setText("Lastname");

        txtProfileLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblProfileFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfileFirstname.setText("Birthdate");

        txtProfileBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblProfileLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfileLastname.setText("Gender");

        lblProfileGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfileGender.setText("Email");

        txtProfileEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblProfileBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfileBirthdate.setText("Phone");

        txtProfilePhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblProfileEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfileEmail.setText("Address");

        txtProfileAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtProfilePassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblProfilePhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfilePhone.setText("Password");

        lblProfileAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfileAddress.setText("Password confirmation");

        txtProfileConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        btnUpdateProfile.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnUpdateProfile.setText("Save");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });

        lblProfileUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfileUsername.setText("User");

        txtProfileUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cmbProfileGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbProfileGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(pnlAppointments);
        pnlAppointments.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblPatientSubtitle)
                .addGap(18, 18, 18)
                .addComponent(txtProfileFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblPatientTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProfileBirthdate)
                        .addGap(18, 18, 18)
                        .addComponent(txtProfilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblProfileEmail)
                        .addGap(18, 18, 18)
                        .addComponent(txtProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtProfileLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblProfileFirstname)
                        .addGap(18, 18, 18)
                        .addComponent(txtProfileBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblProfileLastname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProfileGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblProfileGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(txtProfileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnUpdateProfile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtProfileConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblProfileAddress)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblProfilePhone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProfileUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(lblProfileUsername)))
                            .addComponent(txtProfilePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientSubtitle)
                    .addComponent(txtProfileFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientTitle)
                    .addComponent(txtProfileLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfileFirstname)
                    .addComponent(txtProfileBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfileLastname)
                    .addComponent(lblProfileGender)
                    .addComponent(txtProfileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProfileGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfileBirthdate)
                    .addComponent(txtProfilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfileEmail)
                    .addComponent(txtProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(lblProfileUsername)
                .addGap(18, 18, 18)
                .addComponent(txtProfileUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProfilePhone)
                .addGap(18, 18, 18)
                .addComponent(txtProfilePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProfileAddress)
                .addGap(18, 18, 18)
                .addComponent(txtProfileConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnUpdateProfile)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tabPatientMain.addTab("Modify info", pnlAppointments);

        lblProfilePassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfilePassword.setText("Request medical appointment");

        rdbAppointmentBySpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rdbAppointmentBySpecialty.setText("Specialty");
        rdbAppointmentBySpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAppointmentBySpecialtyActionPerformed(evt);
            }
        });

        rdbAppointmentByDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rdbAppointmentByDoctor.setText("Doctor");
        rdbAppointmentByDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAppointmentByDoctorActionPerformed(evt);
            }
        });

        sepAppointments.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblProfileConfirmPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblProfileConfirmPassword.setText("Appointment date");

        txtAppointmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtAppointmentTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAppointmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentType.setText("Appointment time");

        lblAppointmentDoctorOrSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentDoctorOrSpecialty.setText("Appointment type");

        lblAppointmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentDate.setText("Appointment reason");

        cmbAppointmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAppointmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));

        btnRequestAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRequestAppointment.setText("Create");
        btnRequestAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestAppointmentActionPerformed(evt);
            }
        });

        sepProfile.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblAppointmentTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointmentTime.setText("Request hospitalization");

        lblAppointmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentReason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointmentReason.setText("Hospitalization reason");

        lblHospitalizationReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationReason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationReason.setText("Attending doctor");

        cmbHospitalizationDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbHospitalizationDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtHospitalizationDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblHospitalizationDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationDate.setText("Estimated date of admission");
        lblHospitalizationDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblHospitalizationDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationDoctor.setText("Desired room type");

        cmbHospitalizationRoomType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbHospitalizationRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblHospitalizationRoomType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationRoomType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationRoomType.setText("Observations");

        txtAreaHospitalizationObservations.setColumns(20);
        txtAreaHospitalizationObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAreaHospitalizationObservations.setRows(5);
        scrAppointmentsTable.setViewportView(txtAreaHospitalizationObservations);

        btnRequestHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRequestHospitalization.setText("Create");
        btnRequestHospitalization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestHospitalizationActionPerformed(evt);
            }
        });

        lblHospitalizationObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationObservations.setText("Cancel appointment");

        lblCancelAppointmentId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCancelAppointmentId.setText("ID appointment");

        lblCancelObservation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCancelObservation.setText("Observations");

        txtAreaCancelObservation.setColumns(20);
        txtAreaCancelObservation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAreaCancelObservation.setRows(5);
        scrHospitalizationObservations.setViewportView(txtAreaCancelObservation);

        btnCancelAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCancelAppointment.setText("Cancel");
        btnCancelAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAppointmentActionPerformed(evt);
            }
        });

        txtAreaHospitalizationReason.setColumns(20);
        txtAreaHospitalizationReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAreaHospitalizationReason.setRows(5);
        scrAppointmentReason.setViewportView(txtAreaHospitalizationReason);

        txtAreaAppointmentReason.setColumns(20);
        txtAreaAppointmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAreaAppointmentReason.setRows(5);
        scrCancelObservation.setViewportView(txtAreaAppointmentReason);

        cmbCancelAppointmentId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbCancelAppointmentId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        cmbAppointmentDoctorOrSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAppointmentDoctorOrSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(pnlHospitalization);
        pnlHospitalization.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rdbAppointmentBySpecialty)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdbAppointmentByDoctor))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAppointmentType)
                                        .addComponent(lblProfileConfirmPassword)
                                        .addComponent(cmbAppointmentDoctorOrSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(lblAppointmentDate))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(lblAppointmentDoctorOrSpecialty))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(cmbAppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(lblProfilePassword)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(scrCancelObservation, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnRequestAppointment)))
                .addGap(69, 69, 69)
                .addComponent(sepAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(btnRequestHospitalization))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblAppointmentReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrAppointmentReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(lblAppointmentTime, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(lblHospitalizationReason, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHospitalizationRoomType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHospitalizationDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scrAppointmentsTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHospitalizationDoctor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(cmbHospitalizationDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(txtHospitalizationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(cmbHospitalizationRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(sepProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrHospitalizationObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblHospitalizationObservations))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnCancelAppointment))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbCancelAppointmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCancelAppointmentId)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblCancelObservation)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepAppointments)
            .addComponent(sepProfile)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAppointmentTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(lblAppointmentReason)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrAppointmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHospitalizationReason)
                        .addGap(18, 18, 18)
                        .addComponent(cmbHospitalizationDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHospitalizationDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHospitalizationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblHospitalizationDoctor)
                        .addGap(18, 18, 18)
                        .addComponent(cmbHospitalizationRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHospitalizationRoomType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrAppointmentsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRequestHospitalization)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblProfilePassword)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdbAppointmentBySpecialty)
                                    .addComponent(rdbAppointmentByDoctor))
                                .addGap(18, 18, 18)
                                .addComponent(cmbAppointmentDoctorOrSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblProfileConfirmPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(lblAppointmentType)
                                .addGap(18, 18, 18)
                                .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAppointmentDate)
                                .addGap(24, 24, 24)
                                .addComponent(scrCancelObservation, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblHospitalizationObservations)
                                .addGap(39, 39, 39)
                                .addComponent(lblCancelAppointmentId)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCancelAppointmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCancelObservation)
                                .addGap(18, 18, 18)
                                .addComponent(scrHospitalizationObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnCancelAppointment)))
                        .addGap(18, 18, 18)
                        .addComponent(lblAppointmentDoctorOrSpecialty)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnRequestAppointment)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabPatientMain.addTab("Request/Cancel", pnlHospitalization);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPatientMain)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(pnlTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPatientMain))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void pnlTitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (cmbCancelAppointmentId.getSelectedIndex() <= 0) {
            return;
        }
        HashMap<String, String> data = new HashMap<>();
        data.put("appointmentId", cmbCancelAppointmentId.getSelectedItem().toString());
        data.put("observation", txtAreaCancelObservation.getText());
        ViewHelper.handleResponse(this, context.getAppointmentController().cancelAppointment(data), () -> {
            txtAreaCancelObservation.setText("");
            refreshAppointmentsTable();
        });
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        HashMap<String, String> data = new HashMap<>();
        data.put("currentId", String.valueOf(patient.getId()));
        data.put("firstname", txtProfileFirstname.getText());
        data.put("lastname", txtProfileLastname.getText());
        data.put("gender", cmbProfileGender.getSelectedIndex() == 0 ? "" : String.valueOf(cmbProfileGender.getSelectedIndex() == 1));
        data.put("birthdate", txtProfileBirthdate.getText());
        data.put("address", txtProfileAddress.getText());
        data.put("phone", txtProfilePhone.getText());
        data.put("email", txtProfileEmail.getText());
        data.put("username", txtProfileUsername.getText());
        data.put("password", txtProfilePassword.getText());
        data.put("confirmPassword", txtProfileConfirmPassword.getText());

        ViewHelper.handleResponse(this, context.getPatientController().updatePatient(data), () -> {
            this.patient = (Patient) context.findUserById(patient.getId());
            loadPatientProfile();
        });
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        context.setCurrentUser(null);
        this.setVisible(false);
        new LoginView().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnBackToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        new AdminView(user).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void rdbAppointmentBySpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (rdbAppointmentByDoctor.isSelected()) {
            rdbAppointmentByDoctor.setSelected(false);
        }
        cmbAppointmentDoctorOrSpecialty.removeAllItems();
        cmbAppointmentDoctorOrSpecialty.addItem("Select one");
        for (Specialty specialty : Specialty.values()) {
            cmbAppointmentDoctorOrSpecialty.addItem(SpecialtyMapper.toDisplayName(specialty));
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void rdbAppointmentByDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if (rdbAppointmentBySpecialty.isSelected()) {
            rdbAppointmentBySpecialty.setSelected(false);
        }
        cmbAppointmentDoctorOrSpecialty.removeAllItems();
        cmbAppointmentDoctorOrSpecialty.addItem("Select one");
        Response response = context.getDoctorController().getAllDoctors();
        if (response.getData() == null) {
            return;
        }
        List<HashMap<String, Object>> doctors = (List<HashMap<String, Object>>) response.getData().get("doctors");
        for (HashMap<String, Object> doctor : doctors) {
            cmbAppointmentDoctorOrSpecialty.addItem(doctor.get("id") + " - " + doctor.get("label"));
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btnRequestAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HashMap<String, String> data = new HashMap<>();
        data.put("patientId", String.valueOf(patient.getId()));
        data.put("date", txtAppointmentDate.getText());
        data.put("time", txtAppointmentTime.getText());
        data.put("reason", txtAreaAppointmentReason.getText());
        data.put("appointmentType", String.valueOf(cmbAppointmentType.getSelectedIndex() == 2));
        data.put("byDoctor", String.valueOf(rdbAppointmentByDoctor.isSelected()));

        if (rdbAppointmentByDoctor.isSelected()) {
            String selected = cmbAppointmentDoctorOrSpecialty.getSelectedItem().toString();
            data.put("doctorId", selected.split(" - ")[0]);
        } else {
            data.put("specialty", cmbAppointmentDoctorOrSpecialty.getSelectedItem().toString());
        }

        ViewHelper.handleResponse(this, context.getAppointmentController().requestAppointment(data), () -> {
            txtAppointmentDate.setText("");
            txtAppointmentTime.setText("");
            txtAreaAppointmentReason.setText("");
            refreshAppointmentsTable();
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRefreshAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        refreshAppointmentsTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnRequestHospitalizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (cmbHospitalizationDoctor.getSelectedIndex() <= 0) {
            return;
        }
        HashMap<String, String> data = new HashMap<>();
        data.put("patientId", String.valueOf(patient.getId()));
        data.put("doctorId", cmbHospitalizationDoctor.getSelectedItem().toString().split(" - ")[0]);
        data.put("date", txtHospitalizationDate.getText());
        data.put("reason", txtAreaHospitalizationReason.getText());
        data.put("roomType", cmbHospitalizationRoomType.getSelectedItem().toString());
        data.put("observations", txtAreaHospitalizationObservations.getText());

        ViewHelper.handleResponse(this, context.getHospitalizationController().requestHospitalization(data), () -> {
            txtHospitalizationDate.setText("");
            txtAreaHospitalizationObservations.setText("");
            txtAreaHospitalizationReason.setText("");
        });
    }//GEN-LAST:event_jButton4ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnRequestAppointment;
    private javax.swing.JButton btnRequestHospitalization;
    private javax.swing.JButton btnCancelAppointment;
    private javax.swing.JButton btnRefreshAppointments;
    private javax.swing.JButton btnBackToAdmin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JComboBox<String> cmbAppointmentType;
    private javax.swing.JComboBox<String> cmbHospitalizationDoctor;
    private javax.swing.JComboBox<String> cmbHospitalizationRoomType;
    private javax.swing.JComboBox<String> cmbCancelAppointmentId;
    private javax.swing.JComboBox<String> cmbAppointmentDoctorOrSpecialty;
    private javax.swing.JComboBox<String> cmbProfileGender;
    private javax.swing.JLabel lblPatientHeader;
    private javax.swing.JLabel lblProfilePhone;
    private javax.swing.JLabel lblProfileAddress;
    private javax.swing.JLabel lblProfileUsername;
    private javax.swing.JLabel lblProfilePassword;
    private javax.swing.JLabel lblProfileConfirmPassword;
    private javax.swing.JLabel lblAppointmentType;
    private javax.swing.JLabel lblAppointmentDoctorOrSpecialty;
    private javax.swing.JLabel lblAppointmentDate;
    private javax.swing.JLabel lblAppointmentTime;
    private javax.swing.JLabel lblAppointmentReason;
    private javax.swing.JLabel lblPatientSubtitle;
    private javax.swing.JLabel lblHospitalizationReason;
    private javax.swing.JLabel lblHospitalizationDate;
    private javax.swing.JLabel lblHospitalizationDoctor;
    private javax.swing.JLabel lblHospitalizationRoomType;
    private javax.swing.JLabel lblHospitalizationObservations;
    private javax.swing.JLabel lblCancelAppointmentId;
    private javax.swing.JLabel lblCancelObservation;
    private javax.swing.JLabel lblPatientTitle;
    private javax.swing.JLabel lblProfileFirstname;
    private javax.swing.JLabel lblProfileLastname;
    private javax.swing.JLabel lblProfileGender;
    private javax.swing.JLabel lblProfileBirthdate;
    private javax.swing.JLabel lblProfileEmail;
    private javax.swing.JPanel pnlAppointments;
    private javax.swing.JPanel pnlHospitalization;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JRadioButton rdbAppointmentBySpecialty;
    private javax.swing.JRadioButton rdbAppointmentByDoctor;
    private javax.swing.JScrollPane scrAppointmentsTable;
    private javax.swing.JScrollPane scrHospitalizationObservations;
    private javax.swing.JScrollPane scrHospitalizationReason;
    private javax.swing.JScrollPane scrAppointmentReason;
    private javax.swing.JScrollPane scrCancelObservation;
    private javax.swing.JSeparator sepAppointments;
    private javax.swing.JSeparator sepProfile;
    private javax.swing.JTabbedPane tabPatientMain;
    private javax.swing.JTable tblPatientAppointments;
    private javax.swing.JTextArea txtAreaHospitalizationObservations;
    private javax.swing.JTextArea txtAreaCancelObservation;
    private javax.swing.JTextArea txtAreaHospitalizationReason;
    private javax.swing.JTextArea txtAreaAppointmentReason;
    private javax.swing.JTextField txtProfileFirstname;
    private javax.swing.JTextField txtProfileConfirmPassword;
    private javax.swing.JTextField txtProfileUsername;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtHospitalizationDate;
    private javax.swing.JTextField txtProfileLastname;
    private javax.swing.JTextField txtProfileBirthdate;
    private javax.swing.JTextField txtProfileEmail;
    private javax.swing.JTextField txtProfilePhone;
    private javax.swing.JTextField txtProfileAddress;
    private javax.swing.JTextField txtProfilePassword;
    private packagee.PanelRound pnlBackground;
    private packagee.PanelRound pnlTitleBar;
    // End of variables declaration//GEN-END:variables
}
